name: Development Jobs

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        run: task build
      - name: Test
        run: task run test stop
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: task release -- ${{ github.run_id }}.${{ github.run_attempt }}
